---
name: "IFDB"
guid: "0f18c602-5d24-4f88-bb6e-9e59a2efb1cd"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Get movie metadata the Internet Fanedit Database (IFDB)"
description: >
  Fetches metadata for fan edits from fanedit.org, including title, faneditor, genres, rating, and poster.
category: "Metadata"
owner: "raetha"
artifacts:
- "Jellyfin.Plugin.Ifdb.dll"
- "HtmlAgilityPack.dll"
- "SixLabors.ImageSharp.dll"
changelog: >
  Initial release for Jellyfin 10.11
